INSERT INTO vehicle (brand, model) VALUES ('Ford', 'Focus');
INSERT INTO vehicle (brand, model) VALUES ('VW', 'Käfer 1400');
INSERT INTO vehicle (brand, model) VALUES ('Opel', 'Blitz');
INSERT INTO vehicle (brand, model) VALUES ('BMW', 'M3');
INSERT INTO vehicle (brand, model) VALUES ('Mercedes-Benz', 'S-Class');
INSERT INTO vehicle (brand, model) VALUES ('Audi', 'A6');
INSERT INTO vehicle (brand, model) VALUES ('Porsche', '911');
INSERT INTO vehicle (brand, model) VALUES ('Ferrari', '488 GTB');
INSERT INTO vehicle (brand, model) VALUES ('Lamborghini', 'Aventador');
INSERT INTO vehicle (brand, model) VALUES ('Tesla', 'Model S');
INSERT INTO vehicle (brand, model) VALUES ('Jaguar', 'F-Type');
INSERT INTO vehicle (brand, model) VALUES ('Alfa Romeo', 'Giulia');
INSERT INTO vehicle (brand, model) VALUES ('Maserati', 'Quattroporte');
INSERT INTO vehicle (brand, model) VALUES ('McLaren', '720S');
INSERT INTO vehicle (brand, model) VALUES ('Bugatti', 'Chiron');
INSERT INTO vehicle (brand, model) VALUES ('Lotus', 'Evora');
INSERT INTO vehicle (brand, model) VALUES ('Rolls-Royce', 'Phantom');
INSERT INTO vehicle (brand, model) VALUES ('Bentley', 'Continental GT');
INSERT INTO vehicle (brand, model) VALUES ('Aston Martin', 'DB11');
INSERT INTO vehicle (brand, model) VALUES ('Lexus', 'LC 500');
INSERT INTO vehicle (brand, model) VALUES ('Porsche', 'Taycan');
INSERT INTO vehicle (brand, model) VALUES ('Land Rover', 'Range Rover');
INSERT INTO vehicle (brand, model) VALUES ('Volvo', 'XC90');
